

MAIN_SCREEN = 0;
RUN_CONTROL_SCREEN = 1;
PROCESS_SET1_SCREEN = 2;
PROCESS_SET2_SCREEN = 3;
PROCESS_SET3_SCREEN = 4;
PROCESS_START_SCREEN = 5;
PROCESS_GET_SANPLE_SCREEN = 6;
PROCESS_INJECT_SCREEN = 7;
PROCESS_PERISTALTIC_SCREEN = 8;
PROCESS_DISPEL_SCREEN = 9;
PROCESS_READ_SIGNAL_SCREEN = 10;
PROCESS_CALCULATE_SCREEN = 11;
PROCESS_VALVE_CTRL_SCREEN = 12;
PROCESS_WAIT_TIME_SCREEN = 13;
PROCESS_SELECT_SCREEN = 14;
ACTION_SELECT_SCREEN = 15;
RANGE_SET_SCREEN = 16;
RANGE_SELECT_SCREEN = 17;
HAND_OPERATE1_SCREEN = 18;
HAND_OPERATE2_SCREEN = 19;
HAND_OPERATE3_SCREEN = 20;
HAND_OPERATE4_SCREEN = 21;
IN_OUT_SCREEN = 22;
HISTORY_ANALYSIS_SCREEN = 23;
HISTORY_CALIBRATION_SCREEN = 24;
HISTORY_ALARM_SCREEN = 25;
HISTORY_LOG_SCREEN = 26;
SYSTEM_INFO_SCREEN = 27;




